### ISSUE TITLE
refactor `init` and `create_chip` in `Design` class to have static return signature

### ISSUE THREAD

**Issue by reed-foster** [qnngroup/qnngds#78]
#77 
@reed-foster I totally agree with you, the init and create chip of the Design class and module itself are really ugly right now haha... please feel free to reorganize them!! You will see (as you start a new layout) that many small details are yet to be improved.

**Comment by reed-foster** [comment]
easiest fix for now is to return None for ignored quantities (or just return the value passed through) so that at least the number of arguments returned is a constant

**Comment by reed-foster** [comment]
at some point, a refactor seems to have broken `place_on_sample`. I'm following the doc-strings, but it seems like `place_on_sample` gets called incorrectly inside the `Design` class. I want to refactor `Design` so that it doesn't reuse externally defined methods (e.g. `place_on_sample` being defined in two places)
```
Traceback (most recent call last):
  File "/home/reedf/Dropbox (MIT)/6.2600/back_gate_3mask.py", line 134, in <module>
    test_chip()
    ~~~~~~~~~^^
  File "/home/reedf/Dropbox (MIT)/6.2600/back_gate_3mask.py", line 128, in test_chip
    design.place_remaining_devices([d])
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/reedf/miniforge3/envs/qnn/lib/python3.13/site-packages/qnngds/design.py", line 537, in place_remaining_devices
    place_remaining_devices(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        devices_to_place=devices_to_place,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        write_devices_map_txt=write_devices_map_txt,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/reedf/miniforge3/envs/qnn/lib/python3.13/site-packages/qnngds/design.py", line 234, in place_remaining_devices
    if place_on_sample(
       ~~~~~~~~~~~~~~~^
        devices_to_place[0], (col_i, row_i), sample_map, die_w, file_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "/home/reedf/miniforge3/envs/qnn/lib/python3.13/site-packages/qnngds/design.py", line 157, in place_on_sample
    n_cell = round(ref.xsize / die_w)
                   ~~~~~~~~~~^~~~~~~
TypeError: ufunc 'divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
